---
title: "Data_exploration"
author: "Robert Saldivar"
date: "February 12, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of this document is to explore the data and to see how it might look before putting it into the shiny app. This is also a good place to wrangle data.

```{r}
#Loading the packages and will be used to wrangle the data

install.packages("jpeg")
install.packages("grid")
install.packages("RCurl")


library(tidyverse)
library(here)
library(ballr)
library(lubridate)

kobe <- read_csv("data.csv")

```


```{r}
#Renaming the shots made flag so that the written as made or missed

kobe_wrangle <- kobe %>%
  mutate(shot_made = ifelse(shot_made_flag  > 0, "scored", "missed")) 

```



```{r}
#This is going to visualize the graph of shots taken

shot_graph <- ggplot(kobe_wrangle, aes(x = lon, y = lat)) +
  geom_point(aes(color = shot_made))

shot_graph
```

Shots made per game
```{r}

kobeshots <- kobe  %>% 
  drop_na() %>% 
  group_by(game_id) %>% 
  summarize(
    sum(shot_made_flag)
  )
```

Points per game
```{r}

kobepoints <- read_csv("kobepoints.csv") %>% 
  mutate(
  yr_mo_day = lubridate::parse_date_time(game_date,"mdy"),
  yr_mo_day = as.Date(yr_mo_day), 
  ) %>% 
rename("date" = yr_mo_day) %>% 
  group_by(opponent, date) %>% 
  summarize(
    game_score = sum(game_score)
  )

write_csv(kobepoints, "kobepoints2.csv") #write the csv 
```



```{r}
 ggplot(data = kobe, aes(x = loc_x, y = loc_y)) +
      geom_point(aes(color = shot_made)) + 
      xlim(-250, 250) +
      ylim(-50, 420) +
      scale_color_manual(breaks = c("missed", "scored"),
                         values = c("goldenrod1", "purple3"))+
      theme(axis.line=element_blank(),
            axis.text.x=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks=element_blank(),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            panel.background=element_blank(),
            aspect.ratio = 1, 
            plot.background = element_rect(fill = "black")) 
```





